#mysql
spring.datasource.url=jdbc:mysql://localhost:3306/dragon_fruit_market
spring.datasource.username=root
spring.datasource.password=1234

spring.jwt.secret=this_is_a_very_secret_key_for_dragonFruitMarketProject