spring.application.name=dragon_fruit_market

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8282

# local DB
#spring.profiles.active=local

# aiven DB
spring.profiles.active=prod

#baseUrl
server.servlet.context-path=/api

#Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

#logging
logging.level.chainsawman.gesture=DEBUG
logging.level.org.springframework.web=DEBUG

# ses and s3

# common
aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}

# ses
aws.send-mail-from=${ADMIN_EMAIL}
aws.region=${AWS_REGION}

# se
aws.s3.bucket=${AWS_S3_BUCKET}



