spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dragon_fruit_market
    username: root
    password: 1234
  jwt:
    secret: this_is_a_very_secret_key_for_dragon_fruit_market_54321

aws:
  access-key: AKIATQZCSSC35HEGJOO6
  secret-key: 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
  send-mail-from: gimchijjim200@gmail.com
  region: ap-northeast-2
  s3:
    bucket: dragonfruit-242201301175-ap-northeast-2-an

cloud:
  aws:
    stack:
      auto: false
